package lxmaps

// KeyBy returns a map with the keys generated by the given function.
func KeyBy[K comparable, J comparable, V any](m map[K]V, fn func(K, V) J) map[J]V {
	out := make(map[J]V, len(m))
	for k, v := range m {
		out[fn(k, v)] = v
	}
	return out
}
